### ISSUE TITLE
Issue about repeated samples

### ISSUE THREAD

**Issue by Qlinsane1** [mtrussart/CytofRUV#33]
What should i do if i don't have replicated samples in different batch?

**Comment by mtrussart** [comment]
Hi, It depends on the design of your experiment, Ideally you will have replicated samples across all batches. How many batches, samples and replicated samples do you have?

**Comment by Qlinsane1** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    there were 40 samples in my study, divided into 8 group in 2 batch. Both batch 1 and 2 have samples from control group，so can i use the control group as replicated samples？
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 12/6/2021 20:33，Marie ***@***.***> wrote： 



Hi, It depends on the design of your experiment, Ideally you will have replicated samples across all batches. How many batches, samples and replicated samples do you have?

**Comment by mtrussart** [comment]
Hi, 
Sorry for the delay in replying.
I guess, you have samples with some specific condition and other control samples, is that right?
And you only have replicated control samples in batch 1 and 2 but no replicated samples from the other type of samples?
Ideally yes you should have samples from both types, so that you are able to identify the batch present in both types. Unless your control samples and normal samples have quite a similar profile of clusters, is that the case?
